### ISSUE TITLE
Docker fails with file not found error

### ISSUE THREAD

**Issue by Dragonsys** [koillection/koillection-docker#1]
When trying to launch the docker image it fails with the below error, after the setup is complete and it tries to start the server. This is using the latest version of the docker image pushed on 12/20/2021

NOTICE: PHP message: PHP Fatal error:  Failed opening required '/var/www/koillection/var/cache/prod/App_KernelProdContainer.preload.php' (include_path='.:/usr/share/php') in Unknown on line 0

**Comment by benjaminjonard** [comment]
Hello,

Sorry for the late answer, I pushed a new version that should fix the problem

**Comment by Dragonsys** [comment]
Awesome, I will try it out!
